Controllers/FacultiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FinalProject.Data;
using FinalProject.Models;

namespace FinalProject.Controllers
{
    public class FacultiesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FacultiesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Faculties
        public async Task<IActionResult> Index()
        {
              return _context.faculties != null ? 
                          View(await _context.faculties.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.faculties'  is null.");
        }

        // GET: Faculties/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.faculties == null)
            {
                return NotFound();
            }

            var faculty = await _context.faculties
                .FirstOrDefaultAsync(m => m.Id == id);
            if (faculty == null)
            {
                return NotFound();
            }

            return View(faculty);
        }

        // GET: Faculties/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Faculties/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description")] Faculty faculty)
        {
            if (ModelState.IsValid)
            {
                _context.Add(faculty);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(faculty);
        }

        // GET: Faculties/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.faculties == null)
            {
                return NotFound();
            }

            var faculty = await _context.faculties.FindAsync(id);
            if (faculty == null)
            {
                return NotFound();
            }
            return View(faculty);
        }

        // POST: Faculties/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description")] Faculty faculty)
        {
            if (id != faculty.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(faculty);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FacultyExists(faculty.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(faculty);
        }

        // GET: Faculties/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.faculties == null)
            {
                return NotFound();
            }

            var faculty = await _context.faculties
                .FirstOrDefaultAsync(m => m.Id == id);
            if (faculty == null)
            {
                return NotFound();
            }

            return View(faculty);
        }

        // POST: Faculties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.faculties == null)
            {
                return Problem("Entity set 'ApplicationDbContext.faculties'  is null.");
            }
            var faculty = await _context.faculties.FindAsync(id);
            if (faculty != null)
            {
                _context.faculties.Remove(faculty);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FacultyExists(int id)
        {
          return (_context.faculties?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/StudentsController.cs
using FinalProject.Data;
using FinalProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FinalProject.Controllers
{
    public class StudentsController : Controller
    {
        ApplicationDbContext _context;
        IWebHostEnvironment _webHostEnvironment;

        public StudentsController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        [HttpGet]
        public IActionResult GetIndexView(string? search)
        {
            ViewBag.Search = search;
            if(string.IsNullOrEmpty(search) == true)
            {

                return View("Index", _context.students.ToList());

            }
            else
            {
                return View("Index", _context.students.Where(d=>d.FullName.Contains(search)||
                d.Faculty.Contains(search)).ToList());
            }

            
        }

        [HttpGet]
        public IActionResult GetDetailsView(int id)
        {
            Student stud = _context.students.Include(d=> d.Instructors).FirstOrDefault(d => d.Id == id);

            ViewBag.CurrentStud = stud;
            
            if (stud == null)
            {
                return NotFound();
            }
            else
            {
                return View("Details", stud);
            }
        }
        [HttpGet]
        public IActionResult GetCreateView()
        { 

            return View("Create");
        }
        [HttpPost]
        public IActionResult AddNew(Student stud, IFormFile? imageFormFile)
        {
            if (imageFormFile != null) 
            {
                string imageExtension = Path.GetExtension(imageFormFile.FileName);
                Guid imgGuid = Guid.NewGuid();
                string imgName = imgGuid + imageExtension;
                string imgPath = "\\images\\" + imgName;
                stud.ImagePath = imgPath;
                string imgFullPath = _webHostEnvironment.WebRootPath + imgName;

                FileStream imgFileStream = new FileStream(imgFullPath, FileMode.Create);
                imageFormFile.CopyTo(imgFileStream);
                imgFileStream.Dispose();
            }
            else
            {
                stud.ImagePath = "\\images\\No_Image.png";
            }
            
            
            
            
            if (stud.JoinDate < new DateTime(2010, 8, 23))
            {
                ModelState.AddModelError(string.Empty, "Join Date must be after 23 August 2010 ");
            }

            if (ModelState.IsValid == true)
            {
                _context.students.Add(stud);
                _context.SaveChanges();
                return RedirectToAction("GetIndexView");
            }

            else
            {
                return View("Create",stud);
            }
        }

        [HttpGet]
        public IActionResult GetEditView(int id)
        {
            Student student = _context.students.FirstOrDefault(d => d.Id ==id);
                if (student == null)
                {
                    return NotFound() ;
                }
                else
                {
                return View("Edit", student);
                }
            
        }

        [HttpPost]
        public IActionResult EditCurrent(Student stud, IFormFile? imageFormFile)
        {
            if (imageFormFile != null)
            {
                if (stud.ImagePath != "\\images\\No_Image.png")
                {
                    string oldImgFullPath = _webHostEnvironment.WebRootPath + stud.ImagePath;
                    System.IO.File.Delete(oldImgFullPath);
                }
                string imageExtension = Path.GetExtension(imageFormFile.FileName);
                Guid imgGuid = Guid.NewGuid();
                string imgName = imgGuid + imageExtension;
                string imgPath = "\\images\\" + imgName;
                stud.ImagePath = imgPath;
                string imgFullPath = _webHostEnvironment.WebRootPath + imgName;

                FileStream imgFileStream = new FileStream(imgFullPath, FileMode.Create);
                imageFormFile.CopyTo(imgFileStream);
                imgFileStream.Dispose();
            }
          

            if (stud.JoinDate < new DateTime(2010, 8, 23))
            {
                ModelState.AddModelError(string.Empty, "Join Date must be after 23 August 2010 ");
            }

            if (ModelState.IsValid == true)
            {
                _context.students.Update(stud);
                _context.SaveChanges();
                return RedirectToAction("GetIndexView");
            }
            else
            {
                return View("Edit", stud);
            }
        }
        [HttpGet]
        public IActionResult GetDeleteView(int id)
        {
            Student stud = _context.students.Include(d => d.Instructors).FirstOrDefault(d => d.Id == id);

            
            ViewBag.CurrentStud = stud;

            if (stud == null)
            {
                return NotFound();
            }
            else
            {
                return View("Delete", stud);
            }
        }
        [HttpPost]
        public IActionResult DeleteCurrent (int id) 
        {
            Student student = _context.students.FirstOrDefault(d => d.Id == id);
            
            if (student != null && student.ImagePath != "\\images\\No_Image.png")
            {
                string imgFullPath = _webHostEnvironment.WebRootPath + student.ImagePath;
                System.IO.File.Delete(imgFullPath);
            }
            _context.students.Remove(student);
            _context.SaveChanges();

            return RedirectToAction("GetIndexView");

        }

        //https://localhost:7245/Departments/Greetvisitor
        public string GreetVisitor()
        {
            return "Welcome to Our Universty";
        }

        //https://localhost:7245/Departments/GreetUser?firstName=Folan&lastName=AlFolane
        public string GreetUser(string firstName, string lastName)
        {
            return $"Hi {firstName} {lastName}!";
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FinalProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FinalProject.styles.css" asp-append-version="true" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
    <link href="~/css/sketchy.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-Dark bg-Dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FinalProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="GetIndexView"> Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instructors" asp-action="GetIndexView"> Instructors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Faculties" asp-action="Index"> Faculties</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FinalProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_TSContacts.cshtml
<div class="card" style="width:250px">
    For Technical support :
    <i class=" bi bi-envelope">techsupport@university.com</i>
    <i class="bi bi-phone">01134532588</i>
</div>