Models/Instructor.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace FinalProject.Models
{
    public class Instructor
    {
        public int Id { get; set; }

        [DisplayName("Instructor")]

        [Required(ErrorMessage = "You Have to provide a valid fullname.")]
        [MinLength(2, ErrorMessage = "Full name musn't be less than 2 charcters.")]
        [MaxLength(20, ErrorMessage = "Full name musn't excee 20 charcters")]
        public string FullName { get; set; }

        [Required(ErrorMessage = "You Have to provide a valid course name.")]
        [MinLength(2, ErrorMessage = "Course name musn't be less than 2 charcters.")]
        [MaxLength(20, ErrorMessage = "Course name musn't excee 20 charcters")]
        public string CourseName { get; set; }

        [DisplayName("BirthDate")]
        public DateTime BirthDate { get; set; }


        [DisplayName("JoinDate")]
        public DateTime JoinDate { get; set; }

        [DisplayName("IsActive")]
        public bool IsActive { get; set; }

        [Range(1, double.MaxValue, ErrorMessage = "Select a valid Course Name")]
        [DisplayName("Faculty")]
        public int StudentId { get; set; }

        [ValidateNever]
        public Student student { get; set; }

        [DisplayName("Image")]
        [ValidateNever]
        public string ImagePath { get; set; }


    }
}

Controllers/InstructorsController.cs
using FinalProject.Data;
using FinalProject.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace FinalProject.Controllers
{
    public class InstructorsController : Controller
    {
        ApplicationDbContext _context;
        IWebHostEnvironment _webHostEnvironment;

        public InstructorsController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        [HttpGet]
        public IActionResult GetIndexView(string? search)
        {
            ViewBag.Search = search;
            if (string.IsNullOrEmpty(search) == true)
            {

                return View("Index", _context.instructors.ToList());

            }
            else
            {
                return View("Index", _context.instructors.Where(d => d.FullName.Contains(search) ||
                d.CourseName.Contains(search)).ToList());
            }

        }
        [HttpGet]
        public IActionResult GetDetailsView(int id)
        {
            Instructor inst = _context.instructors.Include(e => e.student).FirstOrDefault(e=> e.Id == id);

            if (inst == null)
            {
                return NotFound();
            }
            else
            {
                return View("Details", inst);
            }
        }
        [HttpGet]
        public IActionResult GetCreateView()
        {
           
            ViewBag.AllStudents = _context.students.ToList();
          
            return View("Create");
        }
        [HttpPost]
        public IActionResult AddNew(Instructor inst, IFormFile? imageFormFile)
        {
            if (imageFormFile != null)
            {
                string imageExtension = Path.GetExtension(imageFormFile.FileName);
                Guid imgGuid = Guid.NewGuid();
                string imgName = imgGuid + imageExtension;
                string imgPath = "\\images\\" + imgName;
                inst.ImagePath = imgPath;
                string imgFullPath = _webHostEnvironment.WebRootPath + imgName;

                FileStream imgFileStream = new FileStream(imgFullPath, FileMode.Create);
                imageFormFile.CopyTo(imgFileStream);
                imgFileStream.Dispose();
            }
            else
            {
                inst.ImagePath = "\\images\\No_Image.png";
            }


            if (inst.JoinDate < new DateTime(2010,8,23))
            {
                ModelState.AddModelError(string.Empty, "Join Date must be after 23 August 2010 ");
            }

            if (ModelState .IsValid == true)
            {
                _context.instructors.Add(inst);
                _context.SaveChanges();
                return RedirectToAction("GetIndexView");
            }
            else
            {
                ViewBag.AllStudents = _context.students.ToList();

                return View("Create",inst);
            }
            

           
        }

        [HttpGet]
        public IActionResult GetEditView(int id)
        {
            Instructor instructor = _context.instructors.FirstOrDefault(d => d.Id ==id);
            if (instructor == null)
            {
                return NotFound();
            }
            else
            {
                ViewBag.AllStudents = _context.students.ToList();
                return View("Edit", instructor);
            }

        }

        [HttpPost]
        public IActionResult EditCurrent(Instructor inst, IFormFile? imageFormFile)
        {
            if (imageFormFile != null)
            {
                if (inst.ImagePath != "\\images\\No_Image.png") 
                {
                    string oldImgFullPath = _webHostEnvironment.WebRootPath + inst.ImagePath;
                    System.IO.File.Delete(oldImgFullPath);
                }
                string imageExtension = Path.GetExtension(imageFormFile.FileName);
                Guid imgGuid = Guid.NewGuid();
                string imgName = imgGuid + imageExtension;
                string imgPath = "\\images\\" + imgName;
                 inst.ImagePath = imgPath;
                string imgFullPath = _webHostEnvironment.WebRootPath + imgName;

                FileStream imgFileStream = new FileStream(imgFullPath, FileMode.Create);
                imageFormFile.CopyTo(imgFileStream);
                imgFileStream.Dispose();
            }
         

            if (inst.JoinDate < new DateTime(2010, 8, 23))
            {
                ModelState.AddModelError(string.Empty, "Join Date must be after 23 August 2010 ");
            }

            if (ModelState.IsValid == true)
            {
                _context.instructors.Update(inst);
                _context.SaveChanges();
                return RedirectToAction("GetIndexView");
            }
            else
            {
                ViewBag.AllStudents = _context.students.ToList();
                return View("Edit", inst);
            }
        }

        [HttpGet]
        public IActionResult GetDeleteView(int id) 
        {
            Instructor inst = _context.instructors.Include(e => e.student).FirstOrDefault(e => e.Id == id);
            if (inst == null) 
            {
                return NotFound();
            }
            else
            {
                return View("Delete", inst);
            }
        }
        [HttpPost]
        public IActionResult DeleteCurrent(int id)
        {
            Instructor instructor = _context.instructors.FirstOrDefault(d => d.Id == id);
            if (instructor != null && instructor.ImagePath != "\\images\\No_Image.png")
            {
                string imgFullPath = _webHostEnvironment.WebRootPath + instructor.ImagePath;
                System.IO.File.Delete(imgFullPath);
            }

            _context.instructors.Remove(instructor);
            _context.SaveChanges();

            return RedirectToAction("GetIndexView");

        }
        //https://localhost:7245/Departments/Greetvisitor
        public string GreetVisitor()
        {
            return "Welcome to Our Universty";
        }

        //https://localhost:7245/Departments/GreetUser?firstName=Folan&lastName=AlFolane
        public string GreetUser(string firstName, string lastName)
        {
            return $"Hi {firstName} {lastName}!";
        }
    }
}

Controllers/StudentsController.cs
using FinalProject.Data;
using FinalProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FinalProject.Controllers
{
    public class StudentsController : Controller
    {
        ApplicationDbContext _context;
        IWebHostEnvironment _webHostEnvironment;

        public StudentsController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        [HttpGet]
        public IActionResult GetIndexView(string? search)
        {
            ViewBag.Search = search;
            if(string.IsNullOrEmpty(search) == true)
            {

                return View("Index", _context.students.ToList());

            }
            else
            {
                return View("Index", _context.students.Where(d=>d.FullName.Contains(search)||
                d.Faculty.Contains(search)).ToList());
            }

            
        }

        [HttpGet]
        public IActionResult GetDetailsView(int id)
        {
            Student stud = _context.students.Include(d=> d.Instructors).FirstOrDefault(d => d.Id == id);

            ViewBag.CurrentStud = stud;
            
            if (stud == null)
            {
                return NotFound();
            }
            else
            {
                return View("Details", stud);
            }
        }
        [HttpGet]
        public IActionResult GetCreateView()
        { 

            return View("Create");
        }
        [HttpPost]
        public IActionResult AddNew(Student stud, IFormFile? imageFormFile)
        {
            if (imageFormFile != null) 
            {
                string imageExtension = Path.GetExtension(imageFormFile.FileName);
                Guid imgGuid = Guid.NewGuid();
                string imgName = imgGuid + imageExtension;
                string imgPath = "\\images\\" + imgName;
                stud.ImagePath = imgPath;
                string imgFullPath = _webHostEnvironment.WebRootPath + imgName;

                FileStream imgFileStream = new FileStream(imgFullPath, FileMode.Create);
                imageFormFile.CopyTo(imgFileStream);
                imgFileStream.Dispose();
            }
            else
            {
                stud.ImagePath = "\\images\\No_Image.png";
            }
            
            
            
            
            if (stud.JoinDate < new DateTime(2010, 8, 23))
            {
                ModelState.AddModelError(string.Empty, "Join Date must be after 23 August 2010 ");
            }

            if (ModelState.IsValid == true)
            {
                _context.students.Add(stud);
                _context.SaveChanges();
                return RedirectToAction("GetIndexView");
            }

            else
            {
                return View("Create",stud);
            }
        }

        [HttpGet]
        public IActionResult GetEditView(int id)
        {
            Student student = _context.students.FirstOrDefault(d => d.Id ==id);
                if (student == null)
                {
                    return NotFound() ;
                }
                else
                {
                return View("Edit", student);
                }
            
        }

        [HttpPost]
        public IActionResult EditCurrent(Student stud, IFormFile? imageFormFile)
        {
            if (imageFormFile != null)
            {
                if (stud.ImagePath != "\\images\\No_Image.png")
                {
                    string oldImgFullPath = _webHostEnvironment.WebRootPath + stud.ImagePath;
                    System.IO.File.Delete(oldImgFullPath);
                }
                string imageExtension = Path.GetExtension(imageFormFile.FileName);
                Guid imgGuid = Guid.NewGuid();
                string imgName = imgGuid + imageExtension;
                string imgPath = "\\images\\" + imgName;
                stud.ImagePath = imgPath;
                string imgFullPath = _webHostEnvironment.WebRootPath + imgName;

                FileStream imgFileStream = new FileStream(imgFullPath, FileMode.Create);
                imageFormFile.CopyTo(imgFileStream);
                imgFileStream.Dispose();
            }
          

            if (stud.JoinDate < new DateTime(2010, 8, 23))
            {
                ModelState.AddModelError(string.Empty, "Join Date must be after 23 August 2010 ");
            }

            if (ModelState.IsValid == true)
            {
                _context.students.Update(stud);
                _context.SaveChanges();
                return RedirectToAction("GetIndexView");
            }
            else
            {
                return View("Edit", stud);
            }
        }
        [HttpGet]
        public IActionResult GetDeleteView(int id)
        {
            Student stud = _context.students.Include(d => d.Instructors).FirstOrDefault(d => d.Id == id);

            
            ViewBag.CurrentStud = stud;

            if (stud == null)
            {
                return NotFound();
            }
            else
            {
                return View("Delete", stud);
            }
        }
        [HttpPost]
        public IActionResult DeleteCurrent (int id) 
        {
            Student student = _context.students.FirstOrDefault(d => d.Id == id);
            
            if (student != null && student.ImagePath != "\\images\\No_Image.png")
            {
                string imgFullPath = _webHostEnvironment.WebRootPath + student.ImagePath;
                System.IO.File.Delete(imgFullPath);
            }
            _context.students.Remove(student);
            _context.SaveChanges();

            return RedirectToAction("GetIndexView");

        }

        //https://localhost:7245/Departments/Greetvisitor
        public string GreetVisitor()
        {
            return "Welcome to Our Universty";
        }

        //https://localhost:7245/Departments/GreetUser?firstName=Folan&lastName=AlFolane
        public string GreetUser(string firstName, string lastName)
        {
            return $"Hi {firstName} {lastName}!";
        }
    }
}

Views/Instructors/Create.cshtml
@model Instructor
<h1 class="alert alert-success text-center"> Add New Instructor</h1>

<div class="row">
    <form class="col-4" method="post" asp-controller="Instructors" asp-action="AddNew">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
     <div>
            <label asp-for ="FullName"></label>
            <input type="text" asp-for="FullName" class="form-control" />
            <span asp-validation-for="FullName" class="text-danger"></span>
    </div>
     <div>
            <label asp-for="CourseName"></label>
            <input type="text" asp-for="CourseName" class="form-control" />
            <span asp-validation-for="CourseName" class="text-danger"></span>
     </div>
     <div>
            <label asp-for="BirthDate"></label>
            <input asp-for="BirthDate" class="form-control" />
            <span asp-validation-for="BirthDate" class="text-danger"></span>
     </div>
     <div>
            <label asp-for ="JoinDate"></label>
            <input asp-for="JoinDate" class="form-control" />
            <span asp-validation-for="JoinDate" class="text-danger"></span>
     </div>
     <div>
            <label asp-for ="IsActive" ></label>
            <input asp-for="IsActive" />
     </div>
        <div>
            <label asp-for="StudentId"></label>
            <select asp-for="StudentId" asp-items="@(new SelectList(ViewBag.AllStudents,"Id","Faculty"))" class="form-control">
                <option selected disabled>select..</option>
            </select>
            <span asp-validation-for="StudentId" class=" text-danger "></span>
        </div>
        <div>
            <label asp-for="ImagePath"></label>
            <input type="file" name="imageFormFile" id="imageFormFile" accept=".png,.jpg" class="form-control"
              onchange="SetImgSrc()"/>
        </div>

        <button type="submit" class="btn btn-primary mt-4">Add</button>
</form>

    <img src="" id="studImage" class="col-4 card" style=" object-fit:contain" />
</div>
<a asp-controller="Instructors" asp-action="GetViewIndex">Back To List</a>

@section Scripts
{
    <script>
        function SetImgSrc() {

            document.getElementById("studImage").src = window.URL.createObjectURL(document.getElementById
                ("imageFormFile").files[0]);
        }
    </script>

}


Views/Instructors/Delete.cshtml
@model Instructor
<h1 class="alert alert-danger"> Are You Sure You Want To Delete This ?</h1>

<partial name="_InstData"></partial>


<form method="post" asp-controller="Instructors" asp-action="DeleteCurrent">
    <input type="hidden" asp-for="Id" />
    <button type="submit" class="btn btn-danger">Delete</button>
</form>

<a asp-controller="instructors" asp-action="GetIndexView">Back to list</a>

Views/Instructors/Details.cshtml
@model Instructor
<h1 class="alert alert-warning"> @Model.FullName Details</h1>

<partial name="_InstData"></partial>

<a asp-controller="instructors" asp-action="GetIndexView">Back to list</a>
<partial name="_TSContacts"></partial>

Views/Instructors/Edit.cshtml
@model Instructor
<h1 class="alert alert-success text-center"> Edit Instructor</h1>

<div class="row">
    <form class="col-4" method="post" asp-controller="Instructors" asp-action="EditCurrent" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="ImagePath" />

     <div>
            <label asp-for="FullName"></label>
            <input type="text" asp-for="FullName" class="form-control" />
            <span asp-validation-for="FullName" class="text-danger"></span>
       </div>
     <div>
            <label asp-for="CourseName"></label>
            <input type="text" asp-for="CourseName" class="form-control" />
            <span asp-validation-for="CourseName" class="text-danger"></span>
        </div>
     <div>
            <label asp-for="BirthDate"></label>
            <input asp-for="BirthDate" class="form-control" />
            <span asp-validation-for="BirthDate" class="text-danger"></span>
        </div>
     <div>
            <label asp-for="JoinDate"></label>
            <input asp-for="JoinDate" class="form-control" />
            <span asp-validation-for="JoinDate" class="text-danger"></span>
        </div>
     <div>
            <label asp-for="IsActive"></label>
            <input asp-for="IsActive" />
    </div>
     <div>
          <label asp-for="StudentId"></label>
            <select asp-for="StudentId" asp-items="@(new SelectList(ViewBag.AllStudents,"Id","Faculty"))" class="form-control">
             <option selected disabled>select..</option>
            </select>
            <span asp-validation-for="StudentId" class=" text-danger "></span>
     </div>
        <div>
            <label asp-for="ImagePath"></label>
            <input type="file" name="imageFormFile" id="imageFormFile" accept=".png,.jpg" class="form-control"
                   onchange="SetImgSrc()" />
        </div>
        <button type="submit" class="btn btn-primary mt-4">Edit</button>
</form>
    <img src="@Model.ImagePath" class="card col-4" style="object-fit:contain" />
</div>
<a asp-controller="instructors" asp-action="GetIndexView">Back to list</a>

Views/Instructors/Index.cshtml
@model IEnumerable<Instructor>

<a asp-controller="Instructors" asp-action="GetCreateView" class="btn btn-success mb-1">Add New Instructor</a>

<form method="get" asp-controller="Students" asp-action="GetIndexView">
    <div class="input-group">
    <input type="text" name="search" value="@ViewBag.search" />
    <button type="submit" class="btn btn-secondary input-group-append" ><i class="bi bi-search"></i></button>
    </div>
</form>
<partial name="_TSContacts"></partial>

@if (Model.Count() > 0)
{
    <table class="table table-bordered table-striped table-hover">
        <thead>
            <tr><th>@Html.DisplayNameFor(d=>d.Id)</th>
                <th>@Html.DisplayNameFor(d=>d.FullName)</th>
                <th>@Html.DisplayNameFor(d=>d.CourseName)</th>
                <th>@Html.DisplayNameFor(d=>d.JoinDate)</th>
                <th>@Html.DisplayNameFor(d=> d.ImagePath)</th>
                </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                   <td>@item.FullName</td>
                   <td>@item.CourseName</td>
                   <td>@item.JoinDate</td>
                   <td><img src="@item.ImagePath" /></td>
                  <td>

                        <a asp-controller="Instructors" asp-action="GetDetailsView" asp-route-id="@item.Id"><i class="btn btn-outline-warning bi bi-card-list"></i></a>
                        <a asp-controller="Instructors" asp-action="GetEditView" asp-route-id="@item.Id"><i class="btn btn-outline-primary bi bi-pen-fill"></i></a>
                        <a asp-controller="Instructors" asp-action="GetDeleteView" asp-route-id="@item.Id"><i class="btn btn-outline-success bi bi-trash3-fill"></i></a>
  
                  </td></tr>
            }
        </tbody>
    </table>
}
else
{
    <h1 class="alert alert-danger text-center">there is no Instructors to display</h1>
}
<hr />

@if (Model.Count() > 0)
{
    @foreach (var item in Model)
    {
        <div class="card bg-transparent mb-2 text-black text-center" style="width:18rem;height:12rem;display:inline-block">
            <div class="card-header border-success bg-transparent">
                @item.FullName
            </div>
            <div class="card body border-success bg-transparent">
                <img src="@item.ImagePath" class="card-img-top"/>
                <div class="Card-title">@item.CourseName</div>
                <div class="card-text">Started Join At @item.JoinDate.ToShortDateString()</div>
            </div>
            <div class="card-footer border-success bg-transparent">
                Birth Date Is @item.BirthDate.ToShortDateString()
            </div>
        </div>
    }
}
else
{
    <h1 class="alert alert-danger text-center">there is no Instructors to display</h1>
}

Views/Instructors/_InstData.cshtml
@{
    Instructor instructor = (Instructor)ViewBag.CurrentStud;
}

<div class="row">
    <dl class="col-6 row">
    <dt class="col-2"> @Html.DisplayNameFor(d => instructor.Id)</dt>
    <dd class="col-10">@Html.DisplayFor(d => instructor.Id) </dd>
    <dt class="col-2"> @Html.DisplayNameFor(d => instructor.FullName)</dt>
    <dd class="col-10"> @Html.DisplayFor(d => instructor.FullName) </dd>
    <dt class="col-2"> @Html.DisplayNameFor(d => instructor.CourseName)</dt>
    <dd class="col-10">@Html.DisplayFor(d => instructor.CourseName) </dd>
    <dd class="col-10"> @Html.DisplayFor(d => instructor.BirthDate) | @Model.BirthDate</dd>
    <dt class="col-2"> @Html.DisplayNameFor(d => instructor.JoinDate)</dt>
    <dd class="col-10"> @Html.DisplayFor(d => instructor.JoinDate) | @Model.JoinDate</dd>
    <dt class="col-2"> @Html.DisplayNameFor(d => instructor.IsActive)</dt>
    <dd class="col-10"> @Html.DisplayFor(d => instructor.IsActive) | @Model.IsActive</dd>
  </dl>
    <img src="@Model.ImagePath" class="card col-4" style="object-fit:contain" />


 </div>